apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: basic-netapp-iscsi
